# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'extrapolate_dialog.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_extrapolate_Dialog(object):
    def setupUi(self, extrapolate_Dialog):
        extrapolate_Dialog.setObjectName(_fromUtf8("extrapolate_Dialog"))
        extrapolate_Dialog.resize(646, 759)
        self.horizontalLayout = QtGui.QHBoxLayout(extrapolate_Dialog)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.groupBox = QtGui.QGroupBox(extrapolate_Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(140, 0))
        self.groupBox.setMaximumSize(QtCore.QSize(140, 16777215))
        self.groupBox.setTitle(_fromUtf8(""))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(0, 10, 31, 20))
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.well_comboBox = QtGui.QComboBox(self.groupBox)
        self.well_comboBox.setGeometry(QtCore.QRect(40, 10, 81, 20))
        self.well_comboBox.setObjectName(_fromUtf8("well_comboBox"))
        self.log_comboBox = QtGui.QComboBox(self.groupBox)
        self.log_comboBox.setGeometry(QtCore.QRect(10, 60, 111, 20))
        self.log_comboBox.setObjectName(_fromUtf8("log_comboBox"))
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(0, 40, 61, 20))
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.groupBox_2 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_2.setGeometry(QtCore.QRect(0, 440, 141, 231))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.plot_horizon_Button = QtGui.QPushButton(self.groupBox_2)
        self.plot_horizon_Button.setGeometry(QtCore.QRect(60, 200, 65, 23))
        self.plot_horizon_Button.setObjectName(_fromUtf8("plot_horizon_Button"))
        self.horizon_listWidget = QtGui.QListWidget(self.groupBox_2)
        self.horizon_listWidget.setGeometry(QtCore.QRect(10, 20, 121, 171))
        self.horizon_listWidget.setProperty("isWrapping", True)
        self.horizon_listWidget.setObjectName(_fromUtf8("horizon_listWidget"))
        self.groupBox_3 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_3.setGeometry(QtCore.QRect(0, 140, 141, 201))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.fit_Button = QtGui.QPushButton(self.groupBox_3)
        self.fit_Button.setGeometry(QtCore.QRect(0, 80, 65, 23))
        self.fit_Button.setObjectName(_fromUtf8("fit_Button"))
        self.label_3 = QtGui.QLabel(self.groupBox_3)
        self.label_3.setGeometry(QtCore.QRect(0, 10, 71, 20))
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.start_lineEdit = QtGui.QLineEdit(self.groupBox_3)
        self.start_lineEdit.setGeometry(QtCore.QRect(50, 30, 60, 20))
        self.start_lineEdit.setObjectName(_fromUtf8("start_lineEdit"))
        self.end_lineEdit = QtGui.QLineEdit(self.groupBox_3)
        self.end_lineEdit.setGeometry(QtCore.QRect(50, 50, 60, 20))
        self.end_lineEdit.setObjectName(_fromUtf8("end_lineEdit"))
        self.extrapolate_Button = QtGui.QPushButton(self.groupBox_3)
        self.extrapolate_Button.setGeometry(QtCore.QRect(70, 160, 65, 23))
        self.extrapolate_Button.setObjectName(_fromUtf8("extrapolate_Button"))
        self.a_lineEdit = QtGui.QLineEdit(self.groupBox_3)
        self.a_lineEdit.setGeometry(QtCore.QRect(50, 110, 71, 20))
        self.a_lineEdit.setText(_fromUtf8(""))
        self.a_lineEdit.setObjectName(_fromUtf8("a_lineEdit"))
        self.b_lineEdit = QtGui.QLineEdit(self.groupBox_3)
        self.b_lineEdit.setGeometry(QtCore.QRect(50, 130, 71, 20))
        self.b_lineEdit.setText(_fromUtf8(""))
        self.b_lineEdit.setObjectName(_fromUtf8("b_lineEdit"))
        self.draw_Button = QtGui.QPushButton(self.groupBox_3)
        self.draw_Button.setGeometry(QtCore.QRect(0, 160, 65, 23))
        self.draw_Button.setObjectName(_fromUtf8("draw_Button"))
        self.clear_Button = QtGui.QPushButton(self.groupBox_3)
        self.clear_Button.setGeometry(QtCore.QRect(70, 80, 65, 23))
        self.clear_Button.setObjectName(_fromUtf8("clear_Button"))
        self.label_14 = QtGui.QLabel(self.groupBox_3)
        self.label_14.setGeometry(QtCore.QRect(10, 110, 31, 20))
        self.label_14.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.label_15 = QtGui.QLabel(self.groupBox_3)
        self.label_15.setGeometry(QtCore.QRect(10, 130, 31, 20))
        self.label_15.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.label_18 = QtGui.QLabel(self.groupBox_3)
        self.label_18.setGeometry(QtCore.QRect(10, 30, 31, 20))
        self.label_18.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.label_19 = QtGui.QLabel(self.groupBox_3)
        self.label_19.setGeometry(QtCore.QRect(10, 50, 31, 20))
        self.label_19.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(0, 90, 91, 20))
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.sm_log_comboBox = QtGui.QComboBox(self.groupBox)
        self.sm_log_comboBox.setGeometry(QtCore.QRect(10, 110, 111, 20))
        self.sm_log_comboBox.setObjectName(_fromUtf8("sm_log_comboBox"))
        self.groupBox_4 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_4.setGeometry(QtCore.QRect(0, 350, 141, 81))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.save_Button = QtGui.QPushButton(self.groupBox_4)
        self.save_Button.setGeometry(QtCore.QRect(70, 50, 65, 23))
        self.save_Button.setObjectName(_fromUtf8("save_Button"))
        self.lineEdit = QtGui.QLineEdit(self.groupBox_4)
        self.lineEdit.setGeometry(QtCore.QRect(10, 20, 121, 20))
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.horizontalLayout.addWidget(self.groupBox)

        self.retranslateUi(extrapolate_Dialog)
        QtCore.QMetaObject.connectSlotsByName(extrapolate_Dialog)

    def retranslateUi(self, extrapolate_Dialog):
        extrapolate_Dialog.setWindowTitle(_translate("extrapolate_Dialog", "Extrapolate Log", None))
        self.label.setText(_translate("extrapolate_Dialog", "Well", None))
        self.label_2.setText(_translate("extrapolate_Dialog", "Density Log", None))
        self.groupBox_2.setTitle(_translate("extrapolate_Dialog", "Horizons", None))
        self.plot_horizon_Button.setText(_translate("extrapolate_Dialog", "Plot", None))
        self.groupBox_3.setTitle(_translate("extrapolate_Dialog", "Extrapolate", None))
        self.fit_Button.setText(_translate("extrapolate_Dialog", "Fit", None))
        self.label_3.setText(_translate("extrapolate_Dialog", "Interval for fit", None))
        self.start_lineEdit.setToolTip(_translate("extrapolate_Dialog", "Start Depth", None))
        self.start_lineEdit.setText(_translate("extrapolate_Dialog", "1500", None))
        self.end_lineEdit.setToolTip(_translate("extrapolate_Dialog", "End Depth", None))
        self.end_lineEdit.setText(_translate("extrapolate_Dialog", "4000", None))
        self.extrapolate_Button.setText(_translate("extrapolate_Dialog", "Extrapolate", None))
        self.a_lineEdit.setToolTip(_translate("extrapolate_Dialog", "a", None))
        self.b_lineEdit.setToolTip(_translate("extrapolate_Dialog", "b", None))
        self.draw_Button.setText(_translate("extrapolate_Dialog", "Draw", None))
        self.clear_Button.setText(_translate("extrapolate_Dialog", "Clear", None))
        self.label_14.setText(_translate("extrapolate_Dialog", "a:", None))
        self.label_15.setText(_translate("extrapolate_Dialog", "b:", None))
        self.label_18.setText(_translate("extrapolate_Dialog", "start:", None))
        self.label_19.setText(_translate("extrapolate_Dialog", "end:", None))
        self.label_4.setText(_translate("extrapolate_Dialog", "smoothed Density", None))
        self.groupBox_4.setTitle(_translate("extrapolate_Dialog", "Save extrapoalted log", None))
        self.save_Button.setText(_translate("extrapolate_Dialog", "Save", None))
        self.lineEdit.setText(_translate("extrapolate_Dialog", "_extra", None))

