# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1048, 581)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon/icon")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.splitter = QtGui.QSplitter(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.tabWidget = QtGui.QTabWidget(self.splitter)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_map = QtGui.QWidget()
        self.tab_map.setObjectName(_fromUtf8("tab_map"))
        self.tabWidget.addTab(self.tab_map, _fromUtf8(""))
        self.gridLayout.addWidget(self.splitter, 0, 1, 1, 1)
        self.data_listWidget = QtGui.QListWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.data_listWidget.sizePolicy().hasHeightForWidth())
        self.data_listWidget.setSizePolicy(sizePolicy)
        self.data_listWidget.setMinimumSize(QtCore.QSize(100, 0))
        self.data_listWidget.setMaximumSize(QtCore.QSize(160, 16777215))
        self.data_listWidget.setObjectName(_fromUtf8("data_listWidget"))
        self.gridLayout.addWidget(self.data_listWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1048, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuProjects = QtGui.QMenu(self.menubar)
        self.menuProjects.setObjectName(_fromUtf8("menuProjects"))
        self.menuData = QtGui.QMenu(self.menubar)
        self.menuData.setObjectName(_fromUtf8("menuData"))
        self.menuView = QtGui.QMenu(self.menubar)
        self.menuView.setObjectName(_fromUtf8("menuView"))
        self.menuTools = QtGui.QMenu(self.menubar)
        self.menuTools.setObjectName(_fromUtf8("menuTools"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionImport = QtGui.QAction(MainWindow)
        self.actionImport.setObjectName(_fromUtf8("actionImport"))
        self.actionExport = QtGui.QAction(MainWindow)
        self.actionExport.setObjectName(_fromUtf8("actionExport"))
        self.actionSurvey = QtGui.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon/survey_icon")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSurvey.setIcon(icon1)
        self.actionSurvey.setObjectName(_fromUtf8("actionSurvey"))
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionNew = QtGui.QAction(MainWindow)
        self.actionNew.setObjectName(_fromUtf8("actionNew"))
        self.actionMap_view = QtGui.QAction(MainWindow)
        self.actionMap_view.setObjectName(_fromUtf8("actionMap_view"))
        self.actionImport_Multiple = QtGui.QAction(MainWindow)
        self.actionImport_Multiple.setObjectName(_fromUtf8("actionImport_Multiple"))
        self.actionManage_wells = QtGui.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon/data_icon")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionManage_wells.setIcon(icon2)
        self.actionManage_wells.setObjectName(_fromUtf8("actionManage_wells"))
        self.actionNCT = QtGui.QAction(MainWindow)
        self.actionNCT.setObjectName(_fromUtf8("actionNCT"))
        self.actionExtrapolate_Log = QtGui.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon/view_icon")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExtrapolate_Log.setIcon(icon3)
        self.actionExtrapolate_Log.setObjectName(_fromUtf8("actionExtrapolate_Log"))
        self.actionCalculator = QtGui.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon/calculator")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCalculator.setIcon(icon4)
        self.actionCalculator.setObjectName(_fromUtf8("actionCalculator"))
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionCrossploter = QtGui.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon/crossplot")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCrossploter.setIcon(icon5)
        self.actionCrossploter.setObjectName(_fromUtf8("actionCrossploter"))
        self.actionGardner = QtGui.QAction(MainWindow)
        self.actionGardner.setIcon(icon5)
        self.actionGardner.setObjectName(_fromUtf8("actionGardner"))
        self.actionOBP = QtGui.QAction(MainWindow)
        self.actionOBP.setObjectName(_fromUtf8("actionOBP"))
        self.actionDiscern_Shale = QtGui.QAction(MainWindow)
        self.actionDiscern_Shale.setIcon(icon3)
        self.actionDiscern_Shale.setObjectName(_fromUtf8("actionDiscern_Shale"))
        self.actionUpscale_Log = QtGui.QAction(MainWindow)
        self.actionUpscale_Log.setIcon(icon3)
        self.actionUpscale_Log.setObjectName(_fromUtf8("actionUpscale_Log"))
        self.actionSmooth_Log = QtGui.QAction(MainWindow)
        self.actionSmooth_Log.setIcon(icon3)
        self.actionSmooth_Log.setObjectName(_fromUtf8("actionSmooth_Log"))
        self.actionOptimize_Eaton = QtGui.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon/lines")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOptimize_Eaton.setIcon(icon6)
        self.actionOptimize_Eaton.setObjectName(_fromUtf8("actionOptimize_Eaton"))
        self.actionPrediction = QtGui.QAction(MainWindow)
        self.actionPrediction.setObjectName(_fromUtf8("actionPrediction"))
        self.actionCoefficients_Optimization_2 = QtGui.QAction(MainWindow)
        self.actionCoefficients_Optimization_2.setObjectName(_fromUtf8("actionCoefficients_Optimization_2"))
        self.actionPrediction_2 = QtGui.QAction(MainWindow)
        self.actionPrediction_2.setObjectName(_fromUtf8("actionPrediction_2"))
        self.actionOptimize_Bowers = QtGui.QAction(MainWindow)
        self.actionOptimize_Bowers.setIcon(icon6)
        self.actionOptimize_Bowers.setObjectName(_fromUtf8("actionOptimize_Bowers"))
        self.actionEaton = QtGui.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon/pressure")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionEaton.setIcon(icon7)
        self.actionEaton.setObjectName(_fromUtf8("actionEaton"))
        self.actionBowers = QtGui.QAction(MainWindow)
        self.actionBowers.setIcon(icon7)
        self.actionBowers.setObjectName(_fromUtf8("actionBowers"))
        self.menuProjects.addAction(self.actionSurvey)
        self.menuProjects.addAction(self.actionNew)
        self.menuProjects.addSeparator()
        self.menuProjects.addAction(self.actionExit)
        self.menuData.addAction(self.actionImport_Multiple)
        self.menuData.addAction(self.actionImport)
        self.menuData.addAction(self.actionExport)
        self.menuData.addSeparator()
        self.menuData.addAction(self.actionManage_wells)
        self.menuView.addAction(self.actionMap_view)
        self.menuTools.addAction(self.actionSmooth_Log)
        self.menuTools.addAction(self.actionUpscale_Log)
        self.menuTools.addAction(self.actionDiscern_Shale)
        self.menuTools.addAction(self.actionExtrapolate_Log)
        self.menuTools.addSeparator()
        self.menuTools.addAction(self.actionOBP)
        self.menuTools.addAction(self.actionNCT)
        self.menuTools.addAction(self.actionOptimize_Eaton)
        self.menuTools.addAction(self.actionEaton)
        self.menuTools.addAction(self.actionOptimize_Bowers)
        self.menuTools.addAction(self.actionBowers)
        self.menuTools.addSeparator()
        self.menuTools.addAction(self.actionGardner)
        self.menuTools.addAction(self.actionCrossploter)
        self.menuTools.addAction(self.actionCalculator)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuProjects.menuAction())
        self.menubar.addAction(self.menuData.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_map), _translate("MainWindow", "Map View", None))
        self.menuProjects.setTitle(_translate("MainWindow", "Survey", None))
        self.menuData.setTitle(_translate("MainWindow", "Data", None))
        self.menuView.setTitle(_translate("MainWindow", "View", None))
        self.menuTools.setTitle(_translate("MainWindow", "Tools", None))
        self.menuHelp.setTitle(_translate("MainWindow", "Help", None))
        self.actionImport.setText(_translate("MainWindow", "Import Logs", None))
        self.actionExport.setText(_translate("MainWindow", "Export Logs", None))
        self.actionSurvey.setText(_translate("MainWindow", "Setup/Select", None))
        self.actionExit.setText(_translate("MainWindow", "Exit", None))
        self.actionNew.setText(_translate("MainWindow", "New", None))
        self.actionMap_view.setText(_translate("MainWindow", "Map view", None))
        self.actionImport_Multiple.setText(_translate("MainWindow", "Import Multiple Wells", None))
        self.actionManage_wells.setText(_translate("MainWindow", "Manage wells", None))
        self.actionNCT.setText(_translate("MainWindow", "NCT", None))
        self.actionExtrapolate_Log.setText(_translate("MainWindow", "Extrapolate upward", None))
        self.actionCalculator.setText(_translate("MainWindow", "Calculator", None))
        self.actionAbout.setText(_translate("MainWindow", "About", None))
        self.actionCrossploter.setText(_translate("MainWindow", "Crossploter", None))
        self.actionGardner.setText(_translate("MainWindow", "Gardner", None))
        self.actionOBP.setText(_translate("MainWindow", "OBP", None))
        self.actionDiscern_Shale.setText(_translate("MainWindow", "Discern Shale", None))
        self.actionUpscale_Log.setText(_translate("MainWindow", "Upscale Log", None))
        self.actionSmooth_Log.setText(_translate("MainWindow", "Smooth Log", None))
        self.actionOptimize_Eaton.setText(_translate("MainWindow", "Coefficients(Eaton)", None))
        self.actionPrediction.setText(_translate("MainWindow", "Prediction", None))
        self.actionCoefficients_Optimization_2.setText(_translate("MainWindow", "Coefficients Optimization", None))
        self.actionPrediction_2.setText(_translate("MainWindow", "Prediction", None))
        self.actionOptimize_Bowers.setText(_translate("MainWindow", "Coefficients(Bowers)", None))
        self.actionEaton.setText(_translate("MainWindow", "Eaton", None))
        self.actionBowers.setText(_translate("MainWindow", "Bowers", None))

import resources_rc
