# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'survey_edit.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_surveyEditDialog(object):
    def setupUi(self, surveyEditDialog):
        surveyEditDialog.setObjectName(_fromUtf8("surveyEditDialog"))
        surveyEditDialog.resize(679, 520)
        self.formLayoutWidget = QtGui.QWidget(surveyEditDialog)
        self.formLayoutWidget.setGeometry(QtCore.QRect(20, 10, 391, 61))
        self.formLayoutWidget.setObjectName(_fromUtf8("formLayoutWidget"))
        self.formLayout = QtGui.QFormLayout(self.formLayoutWidget)
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.surveyNameLabel = QtGui.QLabel(self.formLayoutWidget)
        self.surveyNameLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.surveyNameLabel.setObjectName(_fromUtf8("surveyNameLabel"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.surveyNameLabel)
        self.surveyNameLineEdit = QtGui.QLineEdit(self.formLayoutWidget)
        self.surveyNameLineEdit.setObjectName(_fromUtf8("surveyNameLineEdit"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.surveyNameLineEdit)
        self.rangesCoordinateSettingsLabel = QtGui.QLabel(self.formLayoutWidget)
        self.rangesCoordinateSettingsLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.rangesCoordinateSettingsLabel.setObjectName(_fromUtf8("rangesCoordinateSettingsLabel"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.rangesCoordinateSettingsLabel)
        self.settingComboBox = QtGui.QComboBox(self.formLayoutWidget)
        self.settingComboBox.setObjectName(_fromUtf8("settingComboBox"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.settingComboBox)
        self.groupBox_2 = QtGui.QGroupBox(surveyEditDialog)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 80, 551, 121))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayoutWidget_3 = QtGui.QWidget(self.groupBox_2)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(9, 30, 531, 87))
        self.gridLayoutWidget_3.setObjectName(_fromUtf8("gridLayoutWidget_3"))
        self.gridLayout_3 = QtGui.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_14 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_14.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_14.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_3.addWidget(self.label_14, 1, 0, 1, 1)
        self.z_0_spinBox = QtGui.QSpinBox(self.gridLayoutWidget_3)
        self.z_0_spinBox.setMaximumSize(QtCore.QSize(80, 16777215))
        self.z_0_spinBox.setMaximum(20000)
        self.z_0_spinBox.setObjectName(_fromUtf8("z_0_spinBox"))
        self.gridLayout_3.addWidget(self.z_0_spinBox, 2, 1, 1, 1)
        self.crline_0_spinBox = QtGui.QSpinBox(self.gridLayoutWidget_3)
        self.crline_0_spinBox.setMaximumSize(QtCore.QSize(80, 16777215))
        self.crline_0_spinBox.setMaximum(20000)
        self.crline_0_spinBox.setObjectName(_fromUtf8("crline_0_spinBox"))
        self.gridLayout_3.addWidget(self.crline_0_spinBox, 1, 1, 1, 1)
        self.z_1_spinBox = QtGui.QSpinBox(self.gridLayoutWidget_3)
        self.z_1_spinBox.setMaximumSize(QtCore.QSize(80, 16777215))
        self.z_1_spinBox.setMaximum(20000)
        self.z_1_spinBox.setObjectName(_fromUtf8("z_1_spinBox"))
        self.gridLayout_3.addWidget(self.z_1_spinBox, 2, 2, 1, 1)
        self.inline_1_spinBox = QtGui.QSpinBox(self.gridLayoutWidget_3)
        self.inline_1_spinBox.setMaximumSize(QtCore.QSize(80, 16777215))
        self.inline_1_spinBox.setMaximum(20000)
        self.inline_1_spinBox.setObjectName(_fromUtf8("inline_1_spinBox"))
        self.gridLayout_3.addWidget(self.inline_1_spinBox, 0, 2, 1, 1)
        self.crline_1_spinBox = QtGui.QSpinBox(self.gridLayoutWidget_3)
        self.crline_1_spinBox.setMaximumSize(QtCore.QSize(80, 16777215))
        self.crline_1_spinBox.setMaximum(20000)
        self.crline_1_spinBox.setObjectName(_fromUtf8("crline_1_spinBox"))
        self.gridLayout_3.addWidget(self.crline_1_spinBox, 1, 2, 1, 1)
        self.inline_0_spinBox = QtGui.QSpinBox(self.gridLayoutWidget_3)
        self.inline_0_spinBox.setMaximumSize(QtCore.QSize(80, 16777215))
        self.inline_0_spinBox.setMaximum(20000)
        self.inline_0_spinBox.setObjectName(_fromUtf8("inline_0_spinBox"))
        self.gridLayout_3.addWidget(self.inline_0_spinBox, 0, 1, 1, 1)
        self.label_15 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_15.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_15.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_3.addWidget(self.label_15, 2, 0, 1, 1)
        self.z_step_spinBox = QtGui.QSpinBox(self.gridLayoutWidget_3)
        self.z_step_spinBox.setMaximumSize(QtCore.QSize(60, 16777215))
        self.z_step_spinBox.setMaximum(20000)
        self.z_step_spinBox.setObjectName(_fromUtf8("z_step_spinBox"))
        self.gridLayout_3.addWidget(self.z_step_spinBox, 2, 4, 1, 1)
        self.crline_step_spinBox = QtGui.QSpinBox(self.gridLayoutWidget_3)
        self.crline_step_spinBox.setMaximumSize(QtCore.QSize(60, 16777215))
        self.crline_step_spinBox.setMaximum(20000)
        self.crline_step_spinBox.setObjectName(_fromUtf8("crline_step_spinBox"))
        self.gridLayout_3.addWidget(self.crline_step_spinBox, 1, 4, 1, 1)
        self.label_18 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_18.setMaximumSize(QtCore.QSize(60, 16777215))
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout_3.addWidget(self.label_18, 2, 3, 1, 1)
        self.label_16 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_16.setMaximumSize(QtCore.QSize(60, 16777215))
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_3.addWidget(self.label_16, 0, 3, 1, 1)
        self.label_17 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_17.setMaximumSize(QtCore.QSize(60, 16777215))
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_3.addWidget(self.label_17, 1, 3, 1, 1)
        self.inline_step_spinBox = QtGui.QSpinBox(self.gridLayoutWidget_3)
        self.inline_step_spinBox.setMaximumSize(QtCore.QSize(60, 16777215))
        self.inline_step_spinBox.setMaximum(20000)
        self.inline_step_spinBox.setObjectName(_fromUtf8("inline_step_spinBox"))
        self.gridLayout_3.addWidget(self.inline_step_spinBox, 0, 4, 1, 1)
        self.label_13 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_13.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_3.addWidget(self.label_13, 0, 0, 1, 1)
        self.unitComboBox = QtGui.QComboBox(self.gridLayoutWidget_3)
        self.unitComboBox.setMaximumSize(QtCore.QSize(80, 16777215))
        self.unitComboBox.setObjectName(_fromUtf8("unitComboBox"))
        self.gridLayout_3.addWidget(self.unitComboBox, 2, 5, 1, 1)
        self.horizontalLayoutWidget = QtGui.QWidget(surveyEditDialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 470, 651, 41))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.pushButton_5 = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_5.setMaximumSize(QtCore.QSize(100, 23))
        self.pushButton_5.setFlat(False)
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.horizontalLayout.addWidget(self.pushButton_5)
        spacerItem = QtGui.QSpacerItem(170, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.okButton = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.okButton.setMinimumSize(QtCore.QSize(100, 23))
        self.okButton.setMaximumSize(QtCore.QSize(100, 23))
        self.okButton.setObjectName(_fromUtf8("okButton"))
        self.horizontalLayout.addWidget(self.okButton)
        self.cancelButton = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.cancelButton.setMaximumSize(QtCore.QSize(100, 23))
        self.cancelButton.setObjectName(_fromUtf8("cancelButton"))
        self.horizontalLayout.addWidget(self.cancelButton)
        self.pushButton = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.pushButton.setMaximumSize(QtCore.QSize(100, 23))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.horizontalLayout.addWidget(self.pushButton)
        self.groupBox = QtGui.QGroupBox(surveyEditDialog)
        self.groupBox.setGeometry(QtCore.QRect(10, 210, 661, 251))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.tabWidget = QtGui.QTabWidget(self.groupBox)
        self.tabWidget.setGeometry(QtCore.QRect(10, 30, 641, 171))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.simpleTab = QtGui.QWidget()
        self.simpleTab.setObjectName(_fromUtf8("simpleTab"))
        self.gridLayoutWidget = QtGui.QWidget(self.simpleTab)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 621, 121))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_6 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 1, 3, 1, 1)
        self.b_inline_text = QtGui.QLineEdit(self.gridLayoutWidget)
        self.b_inline_text.setMaximumSize(QtCore.QSize(60, 16777215))
        self.b_inline_text.setObjectName(_fromUtf8("b_inline_text"))
        self.gridLayout.addWidget(self.b_inline_text, 1, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 2, 3, 1, 1)
        self.c_x_text = QtGui.QLineEdit(self.gridLayoutWidget)
        self.c_x_text.setMaximumSize(QtCore.QSize(100, 16777215))
        self.c_x_text.setObjectName(_fromUtf8("c_x_text"))
        self.gridLayout.addWidget(self.c_x_text, 2, 4, 1, 1)
        self.b_crline_text = QtGui.QLineEdit(self.gridLayoutWidget)
        self.b_crline_text.setMaximumSize(QtCore.QSize(60, 16777215))
        self.b_crline_text.setObjectName(_fromUtf8("b_crline_text"))
        self.gridLayout.addWidget(self.b_crline_text, 1, 2, 1, 1)
        self.b_y_text = QtGui.QLineEdit(self.gridLayoutWidget)
        self.b_y_text.setMaximumSize(QtCore.QSize(100, 16777215))
        self.b_y_text.setObjectName(_fromUtf8("b_y_text"))
        self.gridLayout.addWidget(self.b_y_text, 1, 5, 1, 1)
        self.c_crline_text = QtGui.QLineEdit(self.gridLayoutWidget)
        self.c_crline_text.setMaximumSize(QtCore.QSize(60, 16777215))
        self.c_crline_text.setObjectName(_fromUtf8("c_crline_text"))
        self.gridLayout.addWidget(self.c_crline_text, 2, 2, 1, 1)
        self.c_inline_text = QtGui.QLineEdit(self.gridLayoutWidget)
        self.c_inline_text.setMaximumSize(QtCore.QSize(60, 16777215))
        self.c_inline_text.setObjectName(_fromUtf8("c_inline_text"))
        self.gridLayout.addWidget(self.c_inline_text, 2, 1, 1, 1)
        self.b_x_text = QtGui.QLineEdit(self.gridLayoutWidget)
        self.b_x_text.setMaximumSize(QtCore.QSize(100, 16777215))
        self.b_x_text.setObjectName(_fromUtf8("b_x_text"))
        self.gridLayout.addWidget(self.b_x_text, 1, 4, 1, 1)
        self.c_y_text = QtGui.QLineEdit(self.gridLayoutWidget)
        self.c_y_text.setMaximumSize(QtCore.QSize(100, 16777215))
        self.c_y_text.setObjectName(_fromUtf8("c_y_text"))
        self.gridLayout.addWidget(self.c_y_text, 2, 5, 1, 1)
        self.label_5 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 0, 3, 1, 1)
        self.a_crline_text = QtGui.QLineEdit(self.gridLayoutWidget)
        self.a_crline_text.setMaximumSize(QtCore.QSize(60, 16777215))
        self.a_crline_text.setObjectName(_fromUtf8("a_crline_text"))
        self.gridLayout.addWidget(self.a_crline_text, 0, 2, 1, 1)
        self.a_x_text = QtGui.QLineEdit(self.gridLayoutWidget)
        self.a_x_text.setMaximumSize(QtCore.QSize(100, 16777215))
        self.a_x_text.setObjectName(_fromUtf8("a_x_text"))
        self.gridLayout.addWidget(self.a_x_text, 0, 4, 1, 1)
        self.a_y_text = QtGui.QLineEdit(self.gridLayoutWidget)
        self.a_y_text.setMaximumSize(QtCore.QSize(100, 16777215))
        self.a_y_text.setObjectName(_fromUtf8("a_y_text"))
        self.gridLayout.addWidget(self.a_y_text, 0, 5, 1, 1)
        self.label_2 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.a_inline_text = QtGui.QLineEdit(self.gridLayoutWidget)
        self.a_inline_text.setMaximumSize(QtCore.QSize(60, 16777215))
        self.a_inline_text.setObjectName(_fromUtf8("a_inline_text"))
        self.gridLayout.addWidget(self.a_inline_text, 0, 1, 1, 1)
        self.label = QtGui.QLabel(self.gridLayoutWidget)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.tabWidget.addTab(self.simpleTab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.gridLayoutWidget_2 = QtGui.QWidget(self.tab_2)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 611, 91))
        self.gridLayoutWidget_2.setObjectName(_fromUtf8("gridLayoutWidget_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_4 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_2.addWidget(self.label_4, 0, 0, 1, 1)
        self.lineEdit_14 = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_14.setObjectName(_fromUtf8("lineEdit_14"))
        self.gridLayout_2.addWidget(self.lineEdit_14, 1, 1, 1, 1)
        self.label_11 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_2.addWidget(self.label_11, 0, 4, 1, 1)
        self.label_10 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_2.addWidget(self.label_10, 1, 2, 1, 1)
        self.lineEdit_16 = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_16.setObjectName(_fromUtf8("lineEdit_16"))
        self.gridLayout_2.addWidget(self.lineEdit_16, 1, 3, 1, 1)
        self.label_8 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_2.addWidget(self.label_8, 1, 0, 1, 1)
        self.lineEdit_13 = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_13.setObjectName(_fromUtf8("lineEdit_13"))
        self.gridLayout_2.addWidget(self.lineEdit_13, 0, 1, 1, 1)
        self.label_9 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_2.addWidget(self.label_9, 0, 2, 1, 1)
        self.lineEdit_15 = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_15.setObjectName(_fromUtf8("lineEdit_15"))
        self.gridLayout_2.addWidget(self.lineEdit_15, 0, 3, 1, 1)
        self.label_12 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_2.addWidget(self.label_12, 1, 4, 1, 1)
        self.lineEdit_17 = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_17.setObjectName(_fromUtf8("lineEdit_17"))
        self.gridLayout_2.addWidget(self.lineEdit_17, 0, 5, 1, 1)
        self.lineEdit_18 = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_18.setObjectName(_fromUtf8("lineEdit_18"))
        self.gridLayout_2.addWidget(self.lineEdit_18, 1, 5, 1, 1)
        self.checkBox = QtGui.QCheckBox(self.tab_2)
        self.checkBox.setGeometry(QtCore.QRect(440, 110, 171, 21))
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.applyButton = QtGui.QPushButton(self.groupBox)
        self.applyButton.setGeometry(QtCore.QRect(540, 210, 100, 23))
        self.applyButton.setObjectName(_fromUtf8("applyButton"))

        self.retranslateUi(surveyEditDialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.cancelButton, QtCore.SIGNAL(_fromUtf8("clicked()")), surveyEditDialog.reject)
        QtCore.QObject.connect(self.okButton, QtCore.SIGNAL(_fromUtf8("clicked()")), surveyEditDialog.accept)
        QtCore.QMetaObject.connectSlotsByName(surveyEditDialog)

    def retranslateUi(self, surveyEditDialog):
        surveyEditDialog.setWindowTitle(_translate("surveyEditDialog", "Survey", None))
        self.surveyNameLabel.setText(_translate("surveyEditDialog", "Survey name", None))
        self.rangesCoordinateSettingsLabel.setText(_translate("surveyEditDialog", "Ranges/coordinate settings", None))
        self.groupBox_2.setTitle(_translate("surveyEditDialog", "Survey ranges:", None))
        self.label_14.setText(_translate("surveyEditDialog", "Cross-line range", None))
        self.label_15.setText(_translate("surveyEditDialog", "Z range", None))
        self.label_18.setText(_translate("surveyEditDialog", "Step", None))
        self.label_16.setText(_translate("surveyEditDialog", "Step", None))
        self.label_17.setText(_translate("surveyEditDialog", "Step", None))
        self.label_13.setText(_translate("surveyEditDialog", "In-line range", None))
        self.pushButton_5.setText(_translate("surveyEditDialog", "Save as", None))
        self.okButton.setText(_translate("surveyEditDialog", "OK", None))
        self.cancelButton.setText(_translate("surveyEditDialog", "Cancel", None))
        self.pushButton.setText(_translate("surveyEditDialog", "Help", None))
        self.groupBox.setTitle(_translate("surveyEditDialog", "Coordiante settings:", None))
        self.label_6.setText(_translate("surveyEditDialog", "= (X,Y)", None))
        self.label_7.setText(_translate("surveyEditDialog", "= (X,Y)", None))
        self.label_5.setText(_translate("surveyEditDialog", "= (X,Y)", None))
        self.label_2.setText(_translate("surveyEditDialog", "Another position on above In-line", None))
        self.label_3.setText(_translate("surveyEditDialog", "Position not on above In-line", None))
        self.label.setText(_translate("surveyEditDialog", "First In-line/Cross-line", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.simpleTab), _translate("surveyEditDialog", "Easy", None))
        self.label_4.setText(_translate("surveyEditDialog", "X = ", None))
        self.label_11.setText(_translate("surveyEditDialog", " + cross-line * ", None))
        self.label_10.setText(_translate("surveyEditDialog", " + in-line * ", None))
        self.label_8.setText(_translate("surveyEditDialog", "Y = ", None))
        self.label_9.setText(_translate("surveyEditDialog", " + in-line * ", None))
        self.label_12.setText(_translate("surveyEditDialog", " + cross-line * ", None))
        self.checkBox.setText(_translate("surveyEditDialog", "Overrule easy settings", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("surveyEditDialog", "Advanced", None))
        self.applyButton.setText(_translate("surveyEditDialog", "Apply", None))

